export const sourcelist = {
  PHONO: 'Skivspelare',
  CD: 'CD',
  TUNER: 'Radio',
  DVD: 'DVD',
  BD: 'BLURAY',
  TV: 'TV',
  'SAT/CBL': 'Satelit',
  MPLAY: 'Apple TV',
  GAME: 'XBOX 360',
  AUX1: 'Aux 1',
  AUX2: 'Aux 2',
  NET: 'Nätverk',
  SPOTIFY: 'Spotify',
  FLICKR: 'flicker',
  FAVORITES: 'favoriter',
  IRADIO: 'webradio',
  SERVER: 'server',
};
